application.name=Themis Application
application.version=1

engine.name=Themis Engine
engine.version=1

path.resources=./data

window.width=800
window.height=600
window.resizable=true
window.maximized=false

renderer.debug=true
renderer.image-count=3
renderer.vsync.enabled=false
renderer.feature.sampler-anisotropy=true
renderer.feature.geometry-shader=true
renderer.feature.fragment-stores-and-atomics=false

scene.projection.fov=60.0f
scene.projection.znear=0.1f
scene.projection.zfar=1400.0f